cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2


language: scala

scala:
   - 2.11.8
   
branches:
  only:
    - solution

jdk:
  - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION test
